version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    VITE_API_URL: /myapp/frontend/api-url

phases:
  install:
    runtime-versions:
      nodejs: 24

  pre_build:
    commands:
      - set -e
      - echo "Logging into Docker Hub..."
      - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin

  build:
    commands:
      - set -e
      - echo "Building frontend image..."

      - docker build \
          --build-arg VITE_API_URL=$VITE_API_URL \
          -t $DOCKER_REGISTRY_USERNAME/projectly-frontend:latest .

      - docker tag $DOCKER_REGISTRY_USERNAME/projectly-frontend:latest $DOCKER_REGISTRY_USERNAME/projectly-frontend:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - set -e
      - echo "Pushing frontend image..."

      - docker push $DOCKER_REGISTRY_USERNAME/projectly-frontend:latest
      - docker push $DOCKER_REGISTRY_USERNAME/projectly-frontend:$CODEBUILD_RESOLVED_SOURCE_VERSION