version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    EC2_INSTANCE_ID: /myapp/ec2/instance-id

phases:
  install:
    runtime-versions:
      nodejs: 24

  pre_build:
    commands:
      - set -e
      - echo "Logging into Docker Hub..."
      - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin

  build:
    commands:
      - set -e
      - echo "Building backend image..."
      - |
        docker build \
        -t $DOCKER_REGISTRY_USERNAME/projectly-backend:latest \
        -f backend/Dockerfile ./backend

      - docker tag $DOCKER_REGISTRY_USERNAME/projectly-backend:latest $DOCKER_REGISTRY_USERNAME/projectly-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - set -e
      - echo "Pushing backend image..."
      - docker push $DOCKER_REGISTRY_USERNAME/projectly-backend:latest
      - docker push $DOCKER_REGISTRY_USERNAME/projectly-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION

      - echo "Deploying to EC2 via SSM..."
      - |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceIds,Values=$EC2_INSTANCE_ID" \
          --region $AWS_DEFAULT_REGION \
          --comment "Deploying $CODEBUILD_RESOLVED_SOURCE_VERSION" \
          --parameters '{
            "commands":[
              "export DOCKER_USERNAME='${DOCKER_REGISTRY_USERNAME}'",
              "export BACKEND_TAG='${CODEBUILD_RESOLVED_SOURCE_VERSION}'",
              "cd /home/ubuntu",
              "docker-compose up -d"
            ]
          }'